### ISSUE TITLE
Get the referral link

### ISSUE THREAD

**Issue by Lyncis** [Volentix/venue-server#158]
We need to get the referral link for the user, so he or she can share it with friends. 
![image](https://user-images.githubusercontent.com/8875863/43593647-5c9092f0-9646-11e8-8470-fe6edfe8a535.png)

**Comment by shawnlauzon** [comment]
I think the referral code makes sense to be stored in the user object, and so returned with the rest of the user data.

The rest of the URL should be constructed on the front-end, because it is the front end which defines what the full URL should be.

Concretely for this example, user contains:

```javascript
{
  ...
  referral_code: user12,
  ...
}
```

And I think the front end can get the current url from `this.$route`, which should then look something like `https://venue.volentix.io/signup?referer=<code>`

**Comment by alexdashkov** [comment]
I confirm that I've added `referral_code` to the `api/retrieve/user/` endpoint. 
About the `signup` endpoint, I'm sending an email with a URL like  `/signup?code=<referral_code>`.

**Comment by shawnlauzon** [comment]
@alexdashkov Yes you're right, I see it in that call. Thanks for the info.

@Lyncis The `retrieve/user` call is done as part of the load user data. So you should find it in the Nuxt store at `this.$store.state.user.referral_code`.

**Comment by Lyncis** [comment]
ok, looks good. Going to try it

**Comment by Lyncis** [comment]
Everything is working, thank you
