### ISSUE TITLE
Prod: Users are earning VTX even when they don't have a signature set

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#215]
**Describe the bug**
Users who previously had a Volentix signature but no longer have this signature set are still earning VTX.

**To Reproduce**
1. Clear the campaign data
2. Wait a few days
3. Look at the dashboard and see that users have some VTX
4. Look at their posts and notice that none of these users have a Volentix signature displayed

**Expected behavior**
Since none of these users have signatures displayed, they should still have 0 VTX

**Screenshots**
After I cleared the data everyone has 0; now they have some points:
![image](https://user-images.githubusercontent.com/611529/44662630-5a702b80-a9dc-11e8-8394-246394517226.png)

I see two problems here:
1) Forum posts exist that are dated before the clearing of the data. That doesn't seem correct.
2) The only two fairly new posts are both credited=false; why then do users have VTX credited on the leaderboard?
![image](https://user-images.githubusercontent.com/611529/44663546-e420f880-a9de-11e8-86c9-d8b7e9938ac8.png)

**Additional context**
I cleared the campaign data on or around 25 September, so there should be no data from before then.

**Comment by joemarct** [comment]
@shawnlauzon This happens because, if I understood the context correctly, you are recycling users from the old db. The system will just think these users have already confirmed their signatures and that they have been scraped before. So, whatever they post from the timestamp of the last scrape or the date they verified their profile are re-scraped and re-credited.

One approach in solving this problem is defining a campaign start. So we create a `Campaign` model that has a `campaign_start` field. (Anyway, we will have to create this model later for the support for multiple campaigns.)

With a campaign with a definite start date, the scraping of posts can be designed so that posts older than the campaign start date will not be scraped.

**Comment by shawnlauzon** [comment]
> The system will just think these users have already confirmed their signatures and that they have been scraped before. So, whatever they posted that is newer than the timestamp of the last scrape or the date they verified their profile are re-scraped and re-credited.

It sounds to me like when these old posts are were re-scraped (and that is perhaps a problem), they should have been re-credited based on the status of their current signature. However, an incorrect assumption was made that their signature was good when it wasn't, and that's where the problem occurred.

It's possible that adding a new `Campaign` model as suggested will solve the problem, but it is a bigger change than what I want to include right now. Furthermore, it would not solve the current problem, which is that posts were credited when they shouldn't have been.

So my solution is just to brute force set these re-scraped posts as not credited:
```
UPDATE public.venue_forumpost SET credited = false WHERE timestamp < '2018-08-25';
```
(note that the timestamp was just so that I could rollback if it was a bad change; in fact we could have removed the `WHERE` clause completely.)

After doing that, all the users again have 0 points, which is all that is needed for this specific problem.

**Comment by shawnlauzon** [comment]
I'm keeping the PR around for the moment, but closing this issue as resolved
